name = "StateCharts"
uuid = "BFC335C0-D564-425B-98AA-D5C699C8B7AB"
license = "MIT"
authors = ["AlgebraicJulia Developer <email@algebraicjulia.org>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[compat]
Catlab = "^0.16"
julia = "1.6"
