name = "StateCharts"
uuid = "bfc335c0-d564-425b-98aa-d5c699c8b7ab"
license = "MIT"
authors = ["AlgebraicJulia Developer <email@algebraicjulia.org>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
GATlab = "f0ffcf3b-d13a-433e-917c-cc44ccf5ead2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Catlab = "^0.16"
GATlab = "0.1.3"
Random = "1.9"
Reexport = "1"
julia = "1.6"
